name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Log versions
        run: |
          node -v
          yarn --version
          git --version

      - name: Log GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "${GITHUB_CONTEXT}"

      - name: Install Packages
        run: yarn install 

      - name: Run Linter ESLint
        run: yarn lint:eslint

      - name: Run Linter Prettier
        run: yarn lint:prettier 

      - name: Run Linter Gherkin
        run: yarn lint:gherkin-lint

      - name: Run Linter Sass
        run: yarn lint:sass-lint

      - name: Commit Linter Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "CI: Linter"
          git add --all
          git diff-index --quiet HEAD || git commit -m "ci(lint):  ${{github.event.commits[0].message}}"

      - name: Build App
        run: yarn build
        
      - name: Run Jest UNIT Tests
        run: yarn test-ci:unit

      - name: Upload test coverage as artifact
        uses: actions/upload-artifact@v1
        with:
          name: coverage
          path: coverage

      - name: Add codecov report
        run: ./node_modules/.bin/codecov -t ${{secrets.CODECOV_TOKEN}}

      - name: Host App locally
        run: yarn start-ci & (sleep 30 && exit)
        #TODO use build instead of devbuilding again
        #run: ./node_modules/.bin/serve -s build -l 3000 & (sleep 30 && exit)

      - name: Setup Files for Puppeteer
        run: |
          sed -i '' 's/headless: false/headless: true/g' features/support/scope/BrowserScope.js

      - name: Run Puppeteer E2E Tests
        run: yarn test-ci:e2e

      - name: Setup Files for Commit
        run: |
          sed -i '' 's/headless: true/headless: false/g' features/support/scope/BrowserScope.js

      - name: Commit Test Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "CI: Test"
          git add --all
          git diff-index --quiet HEAD || git commit -m "ci(testresults): ${{github.event.commits[0].message}}"

      - name: Prerelease 
        run: |
          git config --local user.name "CI: Prerelease"
          yarn prerelease-ci
          
      - name: Push to master
        run: |
          git push "https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git" HEAD:master --follow-tags

      - name: Push copy to stable
        run: |
          git push "https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git" HEAD:stable --follow-tags

      - name: Deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

      - name: Updating Domain
        run: echo "Update domain"
